### ISSUE TITLE
Doesn't work with LaunchPad Mini MK3

### ISSUE THREAD

**Issue by rix0rrr** [duncte123/launchpad.js#2]
Error:

```
Error: Could not find connected launchpad for name "/^Launchpad MK2/"
```

Actual device names:

```
Launchpad Mini MK3 LPMiniMK3 DAW Out
Launchpad Mini MK3 LPMiniMK3 MIDI Out
Launchpad Mini MK3 LPMiniMK3 DAW In
Launchpad Mini MK3 LPMiniMK3 MIDI In
```

**Comment by duncte123** [comment]
As stated in the readme, this library is incompatible with anything but the MK2.

The reason for this being that every launchpad revision uses a different protocol.

Until I own an mk3 i cannot add support for them.

**Comment by duncte123** [comment]
Actually what you could do is something like this 
```js
const lp = new LaunchpadMK2({
    deviceName: /^Launchpad Mini MK3 LPMiniMK3 MIDI/,
    debug: false,
    xyMode: false
});
```
It might work, it might not

**Comment by rix0rrr** [comment]
Totally won't, but I think I figured it out. PR incoming, if you're interested.
